//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;

namespace DOC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Send_Carga
    {
        public decimal VE_ID { get; set; }
        public int VE_TANQ { get; set; }
        public string VE_PROD { get; set; }
        public Nullable<double> VE_LTRI { get; set; }
        public Nullable<double> VE_LTRF { get; set; }
        public string VE_AUM { get; set; }
        public Nullable<double> VE_GCF { get; set; }

        [Required(ErrorMessage = "Ingrese T.A.D.E.")]
        [Display(Name = "T.A.D.E")]
        public string VE_TERM { get; set; }

        [Required]
        [Display(Name = "Tipo de Documento")]
        public string VE_TDOC { get; set; }

        [Required]
        [Display(Name ="Fecha")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "0:yyyy/MM/dd}")]
        public string VE_FDOC { get; set; }

        [Required]
        [Display(Name = "Folio Documento")]
        public string VE_FOLD { get; set; }

        [Required]
        [Display(Name = "Documentado (Litros)")]
        public Nullable<double> VE_VDOC { get; set; }
        public string VE_HFI { get; set; }

        [Required]
        [Display(Name = "Clave de Vehiculo")]
        public string VE_VEHI { get; set; }
        public string VE_TREG { get; set; }

        [Required]
        [Display(Name = "Folio Relacion")]
        public Nullable<decimal> VE_FOLR { get; set; }
        public Nullable<int> VE_NPIP { get; set; }
        public Nullable<int> VE_NDOC { get; set; }
        public Nullable<bool> VE_ENVIO { get; set; }
        public Nullable<decimal> VE_IDC { get; set; }
        public Nullable<System.DateTime> VE_PRDO { get; set; }

        [Required]
        [Display(Name = "Impote en pesos")]
        public Nullable<double> VE_MONTO { get; set; }

        [Required]
        [Display(Name = "R.F.C Proveedor")]
        [RegularExpression("[A-ZÑ&amp;]{3,4}[0-9]{2}[0-1][0-9][0-3][0-9][A-Z0-9]?[A-Z0-9]?[0-9A-Z]", ErrorMessage = "Estructura Invalida")]
        public string VE_RFC { get; set; }
        public int VE_NUMCSGN { get; set; }

        [Required]
        [Display(Name = "Precio")]
        public Nullable<double> VE_PC { get; set; }

        [Required]
        [Display(Name = "Permiso T.A.D.E")]
        public string VE_PAD { get; set; }

        [Required]
        [Display(Name = "Permiso ")]
        public string VE_PERTRA { get; set; }

        [Required]
        [Display(Name = "Nombre Proveedor")]
        public string VE_NOMPROV { get; set; }

        [Required]
        [Display(Name = "Permiso Proveedor")]
        public string VE_PERPROV { get; set; }

        [Required]
        [Display(Name = "Tipo de Documento")]
        public string VE_TP { get; set; }
        public string VE_PI { get; set; }
        public string VE_CLVPRO { get; set; }
        public string VE_CLVSUBPRO { get; set; }
        public string VE_COCGAS { get; set; }
        public string VE_GASETN { get; set; }
        public string VE_CETNGAS { get; set; }
        public string VE_OTROS { get; set; }
        public string VE_MARCA { get; set; }


        
        public int id_list { get; set; }


        [Display(Name = "num")]
        public string fold { get; set; }

        [Display(Name = "Aumento")]
        public string aumento { get; set; }

        [Display(Name = "Fecha")]
        public string fecha { get; set; }
        
       

    }

   

}
