//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace DOC1
{
    using System;
    using System.Collections.Generic;


    public partial class Veeder_Carga
    { 
        public decimal VE_ID { get; set; }

        [Display(Name ="N° Tanque")]
        public int VE_TANQ { get; set; }

        [Display(Name ="Nombre")]
        public string VE_NOM { get; set; }
        public Nullable<double> VE_LTRI { get; set; }
        public Nullable<double> VE_LTRF { get; set; }

        [Display(Name ="Documentado")]
        public Nullable<double> VE_AUM { get; set; }
        public string VE_TERM { get; set; }
        public string VE_TDOC { get; set; }
        public Nullable<System.DateTime> VE_FDOC { get; set; }
        public string VE_FOLD { get; set; }
        public Nullable<double> VE_VDOC { get; set; }

        [Display(Name ="Fecha")]
        public Nullable<System.DateTime> VE_HFI { get; set; }
        public Nullable<double> VE_GCI { get; set; }


        public Nullable<System.DateTime> VE_HFF { get; set; }
        public Nullable<double> VE_GCF { get; set; }
        public Nullable<bool> VE_ENVIO { get; set; }
        public Nullable<bool> VE_MODI { get; set; }
        public Nullable<double> VE_DTAL { get; set; }
        public string VE_FGEN { get; set; }
        public string VE_FILE { get; set; }
        public Nullable<float> LitrosA { get; set; }
        public Nullable<int> VE_VALIDA { get; set; }

        public int DATO { get; set; }

        public int valor { get; set; }
    }
}
